language: ruby
rvm:
  - 2.1.5
  - 2.2.2
gemfile:
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
bundler_args: --quiet
script:
  - bundle exec rake --trace db:create db:migrate test
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
addons:
  code_climate:
    repo_token: 0a20bc52b64df10c299b60f565e4bae3ed78d0abba2b0f7b6ca918f00cb4e673
